import { RARITY_CONFIG, STATUS_EFFECTS } from './config.js';

export const ARENA_ITEM_CATALOG = {
  rust_sword: {
    id: 'rust_sword',
    name: 'Rust Sword',
    category: 'melee',
    slotType: 'weapon',
    rarity: 'common',
    price: 0,
    damage: 22,
    range: 2.7,
    cooldownMs: 540,
    critChance: 0.08,
    critMultiplier: 1.7,
    description: 'Starter blade. Fast enough to survive the first few waves.',
    color: '#c4b39d',
    icon: '⚔️',
    shop: true,
  },
  raider_axe: {
    id: 'raider_axe',
    name: 'Raider Axe',
    category: 'melee',
    slotType: 'weapon',
    rarity: 'rare',
    price: 120,
    damage: 33,
    range: 2.9,
    cooldownMs: 760,
    critChance: 0.12,
    critMultiplier: 1.8,
    description: 'Heavy melee burst for tankier targets.',
    color: '#db8450',
    icon: '🪓',
    shop: true,
  },
  shock_baton: {
    id: 'shock_baton',
    name: 'Shock Baton',
    category: 'melee',
    slotType: 'weapon',
    rarity: 'epic',
    price: 280,
    damage: 28,
    range: 3,
    cooldownMs: 620,
    status: { type: 'freeze', chance: 0.35, durationMs: STATUS_EFFECTS.freeze.durationMs },
    description: 'Chains together quick strikes that slow enemies.',
    color: '#79d7ff',
    icon: '🔱',
    shop: true,
  },
  guardian_hammer: {
    id: 'guardian_hammer',
    name: 'Guardian Hammer',
    category: 'melee',
    slotType: 'weapon',
    rarity: 'legendary',
    price: 0,
    damage: 48,
    range: 3.2,
    cooldownMs: 980,
    splashRadius: 2.4,
    description: 'Rare loot drop. Massive slam damage with splash.',
    color: '#ffd56d',
    icon: '🔨',
    shop: false,
  },
  arena_blaster: {
    id: 'arena_blaster',
    name: 'Arena Blaster',
    category: 'gun',
    slotType: 'weapon',
    rarity: 'rare',
    price: 180,
    damage: 24,
    cooldownMs: 340,
    projectileSpeed: 20,
    projectileLifeMs: 1600,
    spread: 0.015,
    description: 'Reliable ranged sidearm for kiting.',
    color: '#6ac8ff',
    icon: '🔫',
    shop: true,
  },
  scatter_shot: {
    id: 'scatter_shot',
    name: 'Scatter Shot',
    category: 'gun',
    slotType: 'weapon',
    rarity: 'epic',
    price: 360,
    damage: 15,
    cooldownMs: 820,
    projectileSpeed: 18,
    projectileLifeMs: 1300,
    pelletCount: 5,
    spread: 0.12,
    description: 'Close-range burst that clears clustered mobs.',
    color: '#ffb84f',
    icon: '💥',
    shop: true,
  },
  ember_rifle: {
    id: 'ember_rifle',
    name: 'Ember Rifle',
    category: 'gun',
    slotType: 'weapon',
    rarity: 'legendary',
    price: 640,
    damage: 34,
    cooldownMs: 420,
    projectileSpeed: 24,
    projectileLifeMs: 1700,
    status: { type: 'burn', chance: 0.28, durationMs: STATUS_EFFECTS.burn.durationMs },
    description: 'High-end rifle that burns tougher waves down.',
    color: '#ff7e59',
    icon: '🔥',
    shop: true,
  },
  storm_cannon: {
    id: 'storm_cannon',
    name: 'Storm Cannon',
    category: 'gun',
    slotType: 'weapon',
    rarity: 'mythic',
    price: 0,
    damage: 52,
    cooldownMs: 1050,
    projectileSpeed: 18,
    projectileLifeMs: 1900,
    pierce: 2,
    description: 'Mythic drop that punches through entire lines.',
    color: '#d49bff',
    icon: '⚡',
    shop: false,
  },
  frost_nova: {
    id: 'frost_nova',
    name: 'Frost Nova',
    category: 'ability',
    slotType: 'ability',
    rarity: 'rare',
    price: 220,
    damage: 16,
    cooldownMs: 8000,
    radius: 4.2,
    status: { type: 'freeze', chance: 1, durationMs: 2600 },
    description: 'Freezes nearby enemies to create breathing room.',
    color: '#94f2ff',
    icon: '❄️',
    shop: true,
  },
  fire_orb: {
    id: 'fire_orb',
    name: 'Fire Orb',
    category: 'ability',
    slotType: 'ability',
    rarity: 'epic',
    price: 420,
    damage: 42,
    cooldownMs: 6200,
    projectileSpeed: 14,
    projectileLifeMs: 1500,
    radius: 3,
    status: { type: 'burn', chance: 1, durationMs: 4000 },
    description: 'Explosive projectile with guaranteed burn.',
    color: '#ff7f50',
    icon: '☄️',
    shop: true,
  },
  venom_pulse: {
    id: 'venom_pulse',
    name: 'Venom Pulse',
    category: 'ability',
    slotType: 'ability',
    rarity: 'legendary',
    price: 700,
    damage: 24,
    cooldownMs: 5400,
    radius: 5,
    status: { type: 'poison', chance: 1, durationMs: STATUS_EFFECTS.poison.durationMs },
    description: 'Wide pulse that poisons everything around you.',
    color: '#7fe77b',
    icon: '🧪',
    shop: true,
  },
  arc_surge: {
    id: 'arc_surge',
    name: 'Arc Surge',
    category: 'ability',
    slotType: 'ability',
    rarity: 'mythic',
    price: 0,
    damage: 58,
    cooldownMs: 11000,
    radius: 6,
    chainTargets: 5,
    description: 'Mythic chain lightning loot drop.',
    color: '#ffe06b',
    icon: '🌩️',
    shop: false,
  },
  heal_potion: {
    id: 'heal_potion',
    name: 'Heal Potion',
    category: 'consumable',
    slotType: 'utility',
    rarity: 'common',
    price: 0,
    healAmount: 45,
    cooldownMs: 0,
    description: 'Single-use emergency healing.',
    color: '#88ffb0',
    icon: '🧴',
    shop: false,
  },
  berserk_tonic: {
    id: 'berserk_tonic',
    name: 'Berserk Tonic',
    category: 'consumable',
    slotType: 'utility',
    rarity: 'rare',
    price: 0,
    buff: { damageMultiplier: 1.4, durationMs: 9000 },
    description: 'Temporary damage boost during hard waves.',
    color: '#ff99c1',
    icon: '🍷',
    shop: false,
  },
};

export const STARTER_LOADOUT = ['rust_sword', null, null, null, null, null, null, null, null];

export const STARTER_OWNED_ITEMS = ['rust_sword'];

export const SHOP_CATEGORIES = ['melee', 'gun', 'ability'];

export const LOOT_TABLE = [
  { itemId: 'heal_potion', rarity: 'common', weight: 35 },
  { itemId: 'berserk_tonic', rarity: 'rare', weight: 18 },
  { itemId: 'guardian_hammer', rarity: 'legendary', weight: 5 },
  { itemId: 'storm_cannon', rarity: 'mythic', weight: 2 },
  { itemId: 'arc_surge', rarity: 'mythic', weight: 2 },
  { itemId: 'shock_baton', rarity: 'epic', weight: 8 },
  { itemId: 'fire_orb', rarity: 'epic', weight: 10 },
];

export function getCatalogItem(itemId) {
  return ARENA_ITEM_CATALOG[itemId] || null;
}

export function getShopInventory() {
  return Object.values(ARENA_ITEM_CATALOG).filter((item) => item.shop);
}

export function buildClientCatalog() {
  return Object.values(ARENA_ITEM_CATALOG).map((item) => ({
    ...item,
    rarityLabel: RARITY_CONFIG[item.rarity]?.label || item.rarity,
    rarityColor: RARITY_CONFIG[item.rarity]?.color || '#ffffff',
  }));
}
